### ISSUE TITLE
Road to 9th October

### ISSUE THREAD

**Issue by gonmf** [gonmf/matilda#60]
- [x] Decide whether spb or ob take precedence
- [x] Version 20
- [x] 3x3 pattern experiments
- [x] CLOP time factor only; with self-play, 2s/game and OB turned off https://github.com/gonmf/matilda/issues/72
- [x] Generate more thorough O.B. https://github.com/gonmf/matilda/issues/59 (**4a**)
- [x] Benchmark self-play with vs without OB/SPBs
- [x] CLOP playout heuristics; with 400 playouts/turns vs gnugo lvl 0
- [x] Version 21 and merge https://github.com/gonmf/matilda/pull/68
- [ ] CLOP time factor and RAVE; with self-play with about 30s/game and OB turned on  (**5a,6a,S,D**)
- [x] Test using amazon instance or digital ocean instance for tournament play, suggested: c4.2xlarge https://github.com/gonmf/matilda/issues/69
- [ ] Benchmark vs GNU Go for rank estimate
